title: i Light Singapore
url: https://www.ilightsingapore.gov.sg
favicon: /images/iLSGfavicon.ico
colors:
  primary-color: "#000000"
  secondary-color: "#2e2e2e"
  media-colors:
    - title: media-color-one
      color: "#2e2e2e"
    - title: media-color-two
      color: "#2e2e2e"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
description: Asiaâ€™s Leading Sustainable Light Festival held in Marina Bay
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d33k8lpct4fpp1.amplifyapp.com
prod: https://master.d33k8lpct4fpp1.amplifyapp.com
shareicon: /images/iLSGShareBanner.jpg
is_government: false
facebook-pixel: "1272385153390699"
google_analytics: UA-1472842-26
linkedin-insights: ""
resources_name: media-releases
google_analytics_ga4: G-GWG3QCDTVS
